### PR TITLE
Add support for integer battery levels.

### PR DESCRIPTION
**Pull request by Zopieux**
Example code from rtl_433 that outputs int "battery":
https://github.com/merbanan/rtl_433/blob/master/src/devices/ambientweather_tx8300.c#L112

NOTE: parent commit is PR #3 so I could have green tests. Please merge this first, so I can rebase my PR on top of it.

### CODE REVIEW

**Comment by mhansen** [comment]
Looks good to me. I might have messed up the merge order, as this now shows conflicts that need to be resolved before i can merge. Maybe if you pull —rebase then push, I can merge?

**Comment by Zopieux** [comment]
Rebasing right now, hang tight.

**Comment by Zopieux** [comment]
Done :-) Thanks for your quick reviews!

**Comment by mhansen** [comment]
Thank you for upstreaming this :-)

**Pull request merged**
