### PR TITLE
Rebuild location matching to use ID instead of Channel

### PR DESCRIPTION
**Pull request by ducksauz**
At least with the Acurite sensors, the ID is static and has better
cardinality than Channel. The Acurite Tower sensors only have 3
channels available, so if you want to use more than 3, you have to
location match on ID.

### CODE REVIEW

**Comment by mhansen** [comment]
Hi John, thanks for this - it's pretty cool to get your first pull request
:-)

I have a mix of Acurite Tower, Nexus Temperature/Humidity, Ecowitt-WH53
sensors. I think that the nexus and Ecowitt ones have IDs that change
whenever you replace the batteries.

So I think I'd need a way to still dispatch on channel before merging this.

I'm not sure the best design for doing both (honestly, my
semicolon-separated comma-separated values are a bit of a hack), but here's
a first solution that jumped into my mind:

How about offering two flags and iterating through both to find a match,
maybe something like:

--id_matchers=Acurite-Tower,13732,Kitchen;...
--channel_matchers=Nexus Temperature/Humidity,1,Bedroom;...

Or: I just found out that go can actually support repeated flags, which
might be better than semicolon-splitted flags:
https://stackoverflow.com/a/28323276/171898

**Comment by mhansen** [comment]
I've just merged your string|int ID change support in fd02bafafcfd630b0199a147329ef984b55f38d9, thanks!

**Comment by mhansen** [comment]
I moved to taking repeated flags in 7dd8099246028860eea71e176ceaa2c5e9391fe7 and allowed matching off IDs in 7dd8099246028860eea71e176ceaa2c5e9391fe7. Hopefully this will meet your use case?

Try it with 

./rtl_433_prometheus --channel_matcher=EW,1,Bedroom --id_matcher=FD,12345,Downstairs

**Comment by ducksauz** [comment]
Hey Mark,

Thanks for puling in my PR. This looks great on paper, and I presume it'll work just fine for me. I'll give it test this evening to make sure it works in my environment.

Thanks a bunch for making this in the first place. Until I found this, I was staring down the barrel of writing mtail rules to consume the json data and make it available in an exporter.

Best,
-j

**Comment by mhansen** [comment]
Thanks. I'm really glad to hear you're getting some use out of it :-)

**Comment by ducksauz** [comment]
Tested and works great with my 7 sensors and the multiple `-id_matcher` arguments. Thanks again!

**Pull request closed without merging**
